### ISSUE TITLE
Position is always topRight

### ISSUE THREAD

**Issue by christenbc** [koukibadr/Elegant-Notification#108]
no matter how I change the position, it is always top right

**Comment by koukibadr** [comment]
Okay I'll check this bug @christenbc I'll let you know if there's any updates

**Comment by christenbc** [comment]
I had to downgrade to the previous version and it's working well. The current one is buggy

**Comment by koukibadr** [comment]
@christenbc could you try with the latest version published this week ?

**Comment by christenbc** [comment]
It seems fixed now, thanks
