### ISSUE TITLE
Elegant have unnecessary border when config DialogTheme

### ISSUE THREAD

**Issue by Trung15010802** [koukibadr/Elegant-Notification#119]
When i config border for dialog like this Elegant have border too. Can I set it too transparent?

![image](https://github.com/koukibadr/Elegant-Notification/assets/90593296/49fc96db-1309-4175-9f20-9bc83be2b535)

```dart
theme: ThemeData(
colorScheme: ColorScheme.fromSeed(
seedColor: seedColor,
brightness: Brightness.dark,
background: mainBackground,
),
dialogBackgroundColor: mainBackground,
dialogTheme: DialogTheme(
surfaceTintColor: mainBackground,
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(28),
side: const BorderSide(
color: Colors.white,
),
),

```

**Comment by koukibadr** [comment]
@Trung15010802 I just published a new version I added `border` you can customize the border as you want
