### ISSUE TITLE
Notification top position behind notch, not using safe area

### ISSUE THREAD

**Issue by AlexanderThiele** [koukibadr/Elegant-Notification#127]
Hello!
Thanks for the plugin!!

I just implemented it, and it seems that the notification is not using the SafeArea and is appearing behind the top ios notch.

i could not find a way to adjust the top position. any ideas?

<img width="623" alt="image" src="https://github.com/koukibadr/Elegant-Notification/assets/4806327/600c5cd8-3107-45a9-8ff0-30cf219c3ee0">

**Comment by koukibadr** [comment]
@AlexanderThiele I've just published a newer version fixing this bug, check it out and let me know if everything is okay and feel free to close this issue

**Comment by AlexanderThiele** [comment]
Looks good! Thanks for fixing this!
