### ISSUE TITLE
Enable to custom divider in ToastContent

### ISSUE THREAD

**Issue by mminhlequang** [koukibadr/Elegant-Notification#135]
I hope we can have new version for this

<img width="489" alt="Screenshot 2024-09-06 at 14 54 39" src="https://github.com/user-attachments/assets/b0e09ff4-bbd7-440b-abb5-3e9aa9e992ba">

**Comment by koukibadr** [comment]
@mminhlequang nice update it would be okay I'll add to my todo list

**Comment by koukibadr** [comment]
Divider color is now customizable in the latest versions
