### ISSUE TITLE
Need close notification when user tap it

### ISSUE THREAD

**Issue by phucdth12a** [koukibadr/Elegant-Notification#137]
I see we have attribute closeOnTap has been remove at version 1.14.0. And now can close notification after onNotificationPressed.

**Comment by koukibadr** [comment]
@phucdth12a you can programmatically dismiss the notification by calling its `dismiss()` callback
example
```dart
onNotificationPressed: () {
   notification.dismiss();
},
``` 
with `notification` is an `ElegantNotification` class
