### ISSUE TITLE
Same logic for Duration

### ISSUE THREAD

**Issue by maximegorjux** [koukibadr/Elegant-Notification#48]
Hello, it might be good to have the same logic for the duration. Either use Duration for toastDuration as for animationDuration. Or vice versa, use int for animationDuration as toastDuration.
Great package!

**Comment by koukibadr** [comment]
@maximegorjux thanks for the feedback I will work on it
it will be available in the next version

**Comment by koukibadr** [comment]
hello again @maximegorjux the new modifications are published in the new version 1.3.0 
[https://pub.dev/packages/elegant_notification](https://pub.dev/packages/elegant_notification)
feel free to close this issue

**Comment by maximegorjux** [comment]
Hi, perfect, tanks !
