### ISSUE TITLE
ANIMATION.fromBottom

### ISSUE THREAD

**Issue by maximegorjux** [koukibadr/Elegant-Notification#49]
I saw that you added NOTIFICATION_ALIGN.bottom, and that's a great idea! So I think it would be interesting to add ANIMATION.fromBottom

**Comment by koukibadr** [comment]
thanks for the good idea @maximegorjux 
yes I will add it to the animation type options

**Comment by koukibadr** [comment]
modifications are now available in the new version you can set the animation fromBottom in the version 1.4.0
check it out
[https://pub.dev/packages/elegant_notification](https://pub.dev/packages/elegant_notification)

**Comment by maximegorjux** [comment]
Thanks, it works perfectly !
