### ISSUE TITLE
Do a redirection

### ISSUE THREAD

**Issue by maximegorjux** [koukibadr/Elegant-Notification#54]
Hi, again me :)
Because I need it, I thought about adding a way to redirect to a url. If that interests you, I can try to make it as generic as possible, and offer a pull request. Here is a first example:
![image](https://user-images.githubusercontent.com/28810678/148587792-49183895-2927-4077-ad2b-1b5467ffcb83.png)

**Comment by koukibadr** [comment]
Yes for me it will be a good enahcement if we add an action to the notification 
I will add it and if you have any modification you can send me your pull requests at any time 
thanks @maximegorjux

**Comment by maximegorjux** [comment]
Ok super, thanks !

**Comment by koukibadr** [comment]
hello again @maximegorjux the new modifications are published in the new version 1.3.0 check it out if you have any modifications send me your PRs
feel free to close this issue

**Comment by maximegorjux** [comment]
Hi, nice to see this. Thanks
