### ISSUE TITLE
Add width and height

### ISSUE THREAD

**Issue by DevyankShaw** [koukibadr/Elegant-Notification#56]
For the web, it doesn't seem to have a better UX for a small text. If width and height are added then it would be better for customization.

**Comment by koukibadr** [comment]
Thanks for the feedback @DevyankShaw it will be available in the next version

**Comment by koukibadr** [comment]
modifications are now available in the new version 1.4.0
check it out
[https://pub.dev/packages/elegant_notification](https://pub.dev/packages/elegant_notification)

**Comment by koukibadr** [comment]
modifications are now available in the new version 1.4.0
check it out
[https://pub.dev/packages/elegant_notification](https://pub.dev/packages/elegant_notification)

**Comment by DevyankShaw** [comment]
I just checked it, working as expected. Thanks, @koukibadr for the quick release!
