### ISSUE TITLE
onCloseButtonPressed when clicked outside the notification

### ISSUE THREAD

**Issue by maximegorjux** [koukibadr/Elegant-Notification#57]
Hi, thanks again for the work!
I thought it would be cool if the onCloseButtonPressed action was performed if clicked outside the notification. Like the barrierDismissible dialogs

**Comment by koukibadr** [comment]
Hello @maximegorjux thanks for the enhacement ideas 
I will work on it and it will be available in the next version

**Comment by koukibadr** [comment]
@maximegorjux  modifications will be published in the next version
