### ISSUE TITLE
"top right" and "top left" position

### ISSUE THREAD

**Issue by juanquiceno1** [koukibadr/Elegant-Notification#61]
You could add support for lateral alignments, since for large desktop screens these alerts are in the center, I made local adjustments and they look great

`Alignment _getNotificationAlign() {
    switch (widget.notificationPosition) {
      case NOTIFICATION_POSITION.top:
        return Alignment.topCenter;
      case NOTIFICATION_POSITION.topRight:
        return Alignment.topRight;
      case NOTIFICATION_POSITION.topLeft:
        return Alignment.topLeft;
      case NOTIFICATION_POSITION.center:
        return Alignment.center;
      case NOTIFICATION_POSITION.bottom:
        return Alignment.bottomCenter;
      default:
        return Alignment.topCenter;
    }`

`enum NOTIFICATION_POSITION {
  top,
  topRight,
  topLeft,
  center,
  bottom,
}`

**Comment by koukibadr** [comment]
Thanks for the suggsstion I will work on it

**Comment by emmggi** [comment]
Bottom left and bottom right positions too, please.

Thank you.
