### ISSUE TITLE
Publish a new version (update project documentation and changelog)

### ISSUE THREAD

**Issue by koukibadr** [koukibadr/Elegant-Notification#63]

**Comment by avinash-gotluru** [comment]
Hey team can you please update the package I'm facing this issue 

`../../Documents/Src/flutter/.pub-cache/hosted/pub.dartlang.org/elegant_notification-1.5.2/lib/elegant_notification.dart:430:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Documents/Src/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((_) {
`

**Comment by koukibadr** [comment]
Hello @avinash-gotluru I just published a new version of the package that fixes this bug
check it out 
[https://pub.dev/packages/elegant_notification](https://pub.dev/packages/elegant_notification)

**Comment by avinash-gotluru** [comment]
Thank you so much @koukibadr.
