### ISSUE TITLE
Detect when closed

### ISSUE THREAD

**Issue by thorito** [koukibadr/Elegant-Notification#68]
Is it possible to know when the dialog closes?

When the user presses onBack it doesn't fire any closing event, is it possible to know when it closes?

Scenery:
1. Elegant Notification with progressIndicator
2. When the notification is showing the user presses 'on Back'.
3. The notification is hidden/closed.
4. Is it possible to detect that event? <--

Thank you!

**Comment by koukibadr** [comment]
Hello @thorito thanks for the suggesstion
I just added this scenery you can check in the latest version 1.6.2
[https://pub.dev/packages/elegant_notification](https://pub.dev/packages/elegant_notification)

Now when you use  `onDismiss` you will get notified when the back button is pressed (onDismiss is invoked)

**Comment by thorito** [comment]
It has worked well

Thank you
