### ISSUE TITLE
Unhandled Exception: No Overlay widget found.

### ISSUE THREAD

**Issue by acaEpicss** [koukibadr/Elegant-Notification#80]
![Screenshot 2023-03-15 at 10 37 36](https://user-images.githubusercontent.com/127940008/225269139-d354a708-aec7-453d-8d36-5398404474b2.png)
![Screenshot 2023-03-15 at 10 37 50](https://user-images.githubusercontent.com/127940008/225271016-ec1d7655-ac49-47ef-abfd-2e323d4beb85.png)

Apparently there a problem in flutter version 3.7 where you shouldn't use Overlay.of(context) but instead use Overlay.maybeOf(context) if i understand this problem correctly...

Here is a link to similar issue.
https://github.com/flutter/flutter/issues/120591#issuecomment-1431043706

I started getting this problem soon after i upgraded to flutter Flutter (Channel stable, 3.7.7).
If it's maybe just issu for me, any suggestions how to handle this?

**Comment by koukibadr** [comment]
thanks @acaEpicss for filling this issue, a new version has been published [https://pub.dev/packages/elegant_notification](https://pub.dev/packages/elegant_notification)

if everything is okay feel free to close this issue

**Comment by acaEpicss** [comment]
@koukibadr thanks for fast response and fix, as far as i can see it works great now. So I'm closing this issue.
