### ISSUE TITLE
Icons not proper in Arabic mode

### ISSUE THREAD

**Issue by farooq023** [koukibadr/Elegant-Notification#84]
![Screenshot_1683526465](https://user-images.githubusercontent.com/86731412/236749845-fb8b5e17-d31e-4227-b36e-cc17a4962831.png)

The app I am building has localization of 2 languages, English & Arabic. Both of the icons in the notification are not aligned properly in Arabic mode. Kindly see the SS attached. This issue occurs only in Arabic mode, not in English mode.

**Comment by shatanikmahanty** [comment]
@farooq023 it is happening due to missing RTL support in the package. I have added the change in my latest PR.

**Comment by farooq023** [comment]
I am not using RTL/LTR in my project anywhere. I am just localizing, which is itself doing the RTL/LTR. Will your solution work for me?

**Comment by shatanikmahanty** [comment]
Yeah, it will work for that case. i tested by just setting the language to arabic in supportedLocales

**Comment by farooq023** [comment]
Alright, thanks a lot. Is your commit merged now? When can I update the package?

**Comment by shatanikmahanty** [comment]
> Alright, thanks a lot. Is your commit merged now? When can I update the package?

You can update once the repo maintainer approves my changes, till then if you want you can use my fork link in pubspec for a fix

**Comment by farooq023** [comment]
I removed the previous package & added your fork link in pubspec file, and the problem is still there.

**Comment by shatanikmahanty** [comment]
> I removed the previous package & added your fork link in pubspec file, and the problem is still there.

Can you show me the code you are using specifying localisation and the elegant notification?

**Comment by farooq023** [comment]
<img width="285" alt="elegant_noti" src="https://github.com/koukibadr/Elegant-Notification/assets/86731412/037ae970-385c-404c-8411-4394b34c6b91">
Please view the SS attached.

**Comment by shatanikmahanty** [comment]
> <img width="285" alt="elegant_noti" src="https://github.com/koukibadr/Elegant-Notification/assets/86731412/037ae970-385c-404c-8411-4394b34c6b91">
> Please view the SS attached.

Please add below url the branch name.

ref: rtl

**Comment by farooq023** [comment]
Thanks a lot, I added the branch name & it's solved now.
Alright, I will remove the branch name.
I can use the package from your git link until the package is updated in pub.dev.

**Comment by shatanikmahanty** [comment]
> Thanks a lot, I added the branch name & it's solved now.
> Alright, I will remove the branch name.
> I can use the package from your git link until the package is updated in pub.dev.

You're welcome. Happy to help 🙌

**Comment by koukibadr** [comment]
Thanks @farooq023 for filling the issue
@shatanikmahanty amazing job !
the new version is available in pub.dev (1.10.0)

**Comment by shatanikmahanty** [comment]
> Thanks @farooq023 for filling the issue
> @shatanikmahanty amazing job !
> the new version is available in pub.dev (1.10.0)

Thanks @koukibadr. Happy to contribute to this awesome package ✨
