### ISSUE TITLE
Build error toast_content.dart:137

### ISSUE THREAD

**Issue by dpalmeira** [koukibadr/Elegant-Notification#95]
Hello, first of all thank you for your work, it's great!

My issue: When I try to import the latest lib version on my project "elegant_notification **1.11.0**" it fails at build time with the following error:

: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
**toast_content.dart:137**
Try using a constructor or factory that is 'const'.
                  child: const Column(
                               ^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

                      : const EdgeInsets.only(
                          top: verticalComponentPadding,
                          right: horizontalComponentPadding,
                        ),
**Line 137 -->**       child: const Column(
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Icon(

So, if I try the previous version "elegant_notification: **1.10.1"** then it works perfectly, at build time and also by using it, showing the messages as expected.

I don't if it is caused by my app, or it's in fact a bug.

Thank you so much for your help and time.

**Comment by arslancb** [comment]
Bump

**Comment by BobQuasius** [comment]
Still busted. This package worked great a few months ago but now I get errors. I tried old versions, I tried the new versions -- all give me this. I just took this const out of my file and it works fine now. 

![const error](https://github.com/koukibadr/Elegant-Notification/assets/102642255/8f3f8740-a62a-4006-97d3-497133b62fee)
![const line 137](https://github.com/koukibadr/Elegant-Notification/assets/102642255/f81f6db4-a080-4d81-a904-f5dc197ada28)

**Comment by hashtagEsen** [comment]
I have the same issue. 

`../../../.pub-cache/hosted/pub.dev/elegant_notification-1.11.0/lib/widgets/toast_content.dart:137:32: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
                  child: const Column(
                               ^^^^^^
../../../.pub-cache/hosted/pub.dev/elegant_notification-1.11.0/lib/widgets/toast_content.dart:137:32: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
                  child: const Column(
                               ^^^^^^
Restarted application in 496ms.`

Solution: I downgraded to version 1.10.1 and then it works. The new version 1.11.0 seems to have a bug.

**Comment by koukibadr** [comment]
A new version has been published fixing this issue
[https://pub.dev/packages/elegant_notification](https://pub.dev/packages/elegant_notification)

**Comment by koukibadr** [comment]
@dpalmeira feel free to close this issue

**Comment by dpalmeira** [comment]
Hello @koukibadr it works now!

A comment: I have also to make a small change to jump from 1.10.1 to 1.12.0 caused by "notificationPosition will no longer set the alert position instead use position with Alignment type".

Thank you so much for your help and great work.
